from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class ColumnDef:
    """Explicit DuckDB column definition."""

    name: str
    duckdb_type: str
    not_null: bool = False


@dataclass(frozen=True)
class TableDef:
    """Explicit DuckDB table definition."""

    name: str
    columns: tuple[ColumnDef, ...]
    primary_key: tuple[str, ...] = ()


def _create_table_sql(table: TableDef) -> str:
    parts: list[str] = []
    for column in table.columns:
        segment = f'"{column.name}" {column.duckdb_type}'
        if column.not_null:
            segment += " NOT NULL"
        parts.append(segment)
    if table.primary_key:
        joined = ", ".join(f'"{name}"' for name in table.primary_key)
        parts.append(f"PRIMARY KEY ({joined})")
    columns_sql = ",\n                ".join(parts)
    return f"""
        CREATE TABLE IF NOT EXISTS "{table.name}" (
                {columns_sql}
        )
    """


SOURCE_TABLES: tuple[TableDef, ...] = (
    TableDef(
        name="wrds_crsp_daily",
        columns=(
            ColumnDef("permno", "BIGINT", True),
            ColumnDef("permco", "BIGINT"),
            ColumnDef("trade_date", "DATE", True),
            ColumnDef("bid_low", "DOUBLE"),
            ColumnDef("ask_high", "DOUBLE"),
            ColumnDef("price_close", "DOUBLE"),
            ColumnDef("volume", "DOUBLE"),
            ColumnDef("return_total", "DOUBLE"),
            ColumnDef("return_ex_dividend", "DOUBLE"),
            ColumnDef("shares_outstanding_k", "DOUBLE"),
            ColumnDef("price_adjust_factor", "DOUBLE"),
            ColumnDef("share_adjust_factor", "DOUBLE"),
            ColumnDef("trade_count", "BIGINT"),
            ColumnDef("delist_code", "INTEGER"),
            ColumnDef("delist_date", "DATE"),
            ColumnDef("delist_return", "DOUBLE"),
            ColumnDef("delist_return_ex_dividend", "DOUBLE"),
            ColumnDef("delist_price", "DOUBLE"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("ingest_run_id", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("permno", "trade_date"),
    ),
    TableDef(
        name="wrds_compustat_quarterly",
        columns=(
            ColumnDef("gvkey", "VARCHAR", True),
            ColumnDef("datadate", "DATE", True),
            ColumnDef("fyearq", "INTEGER"),
            ColumnDef("fqtr", "INTEGER"),
            ColumnDef("datafqtr", "VARCHAR"),
            ColumnDef("rdq", "DATE"),
            ColumnDef("fyr", "INTEGER"),
            ColumnDef("indfmt", "VARCHAR"),
            ColumnDef("consol", "VARCHAR"),
            ColumnDef("popsrc", "VARCHAR"),
            ColumnDef("datafmt", "VARCHAR"),
            ColumnDef("curcdq", "VARCHAR"),
            ColumnDef("tic", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("saleq", "DOUBLE"),
            ColumnDef("revtq", "DOUBLE"),
            ColumnDef("cogsq", "DOUBLE"),
            ColumnDef("xsgaq", "DOUBLE"),
            ColumnDef("oiadpq", "DOUBLE"),
            ColumnDef("ibq", "DOUBLE"),
            ColumnDef("niq", "DOUBLE"),
            ColumnDef("ibcomq", "DOUBLE"),
            ColumnDef("piq", "DOUBLE"),
            ColumnDef("txtq", "DOUBLE"),
            ColumnDef("xintq", "DOUBLE"),
            ColumnDef("dpq", "DOUBLE"),
            ColumnDef("xrdq", "DOUBLE"),
            ColumnDef("epspxq", "DOUBLE"),
            ColumnDef("epsfxq", "DOUBLE"),
            ColumnDef("cshoq", "DOUBLE"),
            ColumnDef("cshfdq", "DOUBLE"),
            ColumnDef("stkcoq", "DOUBLE"),
            ColumnDef("ucapsq", "DOUBLE"),
            ColumnDef("atq", "DOUBLE"),
            ColumnDef("ltq", "DOUBLE"),
            ColumnDef("seqq", "DOUBLE"),
            ColumnDef("actq", "DOUBLE"),
            ColumnDef("lctq", "DOUBLE"),
            ColumnDef("cheq", "DOUBLE"),
            ColumnDef("finivstq", "DOUBLE"),
            ColumnDef("ivstq", "DOUBLE"),
            ColumnDef("finaoq", "DOUBLE"),
            ColumnDef("ivaoq", "DOUBLE"),
            ColumnDef("finlcoq", "DOUBLE"),
            ColumnDef("findlcq", "DOUBLE"),
            ColumnDef("finltoq", "DOUBLE"),
            ColumnDef("findltq", "DOUBLE"),
            ColumnDef("dlcq", "DOUBLE"),
            ColumnDef("dlttq", "DOUBLE"),
            ColumnDef("rectq", "DOUBLE"),
            ColumnDef("invtq", "DOUBLE"),
            ColumnDef("apq", "DOUBLE"),
            ColumnDef("drcq", "DOUBLE"),
            ColumnDef("gdwlq", "DOUBLE"),
            ColumnDef("intanq", "DOUBLE"),
            ColumnDef("amq", "DOUBLE"),
            ColumnDef("cstkq", "DOUBLE"),
            ColumnDef("retq", "DOUBLE"),
            ColumnDef("aociderglq", "DOUBLE"),
            ColumnDef("aociotherq", "DOUBLE"),
            ColumnDef("aocipenq", "DOUBLE"),
            ColumnDef("aocisecglq", "DOUBLE"),
            ColumnDef("oancfy", "DOUBLE"),
            ColumnDef("capxy", "DOUBLE"),
            ColumnDef("dvq", "DOUBLE"),
            ColumnDef("dvy", "DOUBLE"),
            ColumnDef("ivncfy", "DOUBLE"),
            ColumnDef("fincfy", "DOUBLE"),
            ColumnDef("prstkcy", "DOUBLE"),
            ColumnDef("prccq", "DOUBLE"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("ingest_run_id", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("gvkey", "datadate", "datafqtr", "indfmt", "consol", "popsrc", "datafmt"),
    ),
    TableDef(
        name="wrds_compustat_annual",
        columns=(
            ColumnDef("gvkey", "VARCHAR", True),
            ColumnDef("datadate", "DATE", True),
            ColumnDef("fyear", "INTEGER"),
            ColumnDef("fyr", "INTEGER"),
            ColumnDef("indfmt", "VARCHAR"),
            ColumnDef("consol", "VARCHAR"),
            ColumnDef("popsrc", "VARCHAR"),
            ColumnDef("datafmt", "VARCHAR"),
            ColumnDef("curcd", "VARCHAR"),
            ColumnDef("tic", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("sale", "DOUBLE"),
            ColumnDef("revt", "DOUBLE"),
            ColumnDef("cogs", "DOUBLE"),
            ColumnDef("xsga", "DOUBLE"),
            ColumnDef("oiadp", "DOUBLE"),
            ColumnDef("ib", "DOUBLE"),
            ColumnDef("ni", "DOUBLE"),
            ColumnDef("ibcom", "DOUBLE"),
            ColumnDef("pi", "DOUBLE"),
            ColumnDef("txt", "DOUBLE"),
            ColumnDef("xint", "DOUBLE"),
            ColumnDef("dp", "DOUBLE"),
            ColumnDef("am", "DOUBLE"),
            ColumnDef("xrd", "DOUBLE"),
            ColumnDef("epspx", "DOUBLE"),
            ColumnDef("epsfx", "DOUBLE"),
            ColumnDef("stkco", "DOUBLE"),
            ColumnDef("ucaps", "DOUBLE"),
            ColumnDef("csho", "DOUBLE"),
            ColumnDef("at", "DOUBLE"),
            ColumnDef("lt", "DOUBLE"),
            ColumnDef("seq", "DOUBLE"),
            ColumnDef("act", "DOUBLE"),
            ColumnDef("lct", "DOUBLE"),
            ColumnDef("che", "DOUBLE"),
            ColumnDef("finivst", "DOUBLE"),
            ColumnDef("ivst", "DOUBLE"),
            ColumnDef("finao", "DOUBLE"),
            ColumnDef("ivao", "DOUBLE"),
            ColumnDef("finlco", "DOUBLE"),
            ColumnDef("findlc", "DOUBLE"),
            ColumnDef("finlto", "DOUBLE"),
            ColumnDef("findlt", "DOUBLE"),
            ColumnDef("dlc", "DOUBLE"),
            ColumnDef("dltt", "DOUBLE"),
            ColumnDef("rect", "DOUBLE"),
            ColumnDef("invt", "DOUBLE"),
            ColumnDef("ap", "DOUBLE"),
            ColumnDef("drc", "DOUBLE"),
            ColumnDef("gdwl", "DOUBLE"),
            ColumnDef("intan", "DOUBLE"),
            ColumnDef("cstk", "DOUBLE"),
            ColumnDef("ret", "DOUBLE"),
            ColumnDef("aocidergl", "DOUBLE"),
            ColumnDef("aociother", "DOUBLE"),
            ColumnDef("aocipen", "DOUBLE"),
            ColumnDef("aocisecgl", "DOUBLE"),
            ColumnDef("oancf", "DOUBLE"),
            ColumnDef("capx", "DOUBLE"),
            ColumnDef("dv", "DOUBLE"),
            ColumnDef("dvc", "DOUBLE"),
            ColumnDef("ivncf", "DOUBLE"),
            ColumnDef("fincf", "DOUBLE"),
            ColumnDef("prstkc", "DOUBLE"),
            ColumnDef("prcc_f", "DOUBLE"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("ingest_run_id", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("gvkey", "datadate", "indfmt", "consol", "popsrc", "datafmt"),
    ),
    TableDef(
        name="wrds_compustat_segments_historical",
        columns=(
            ColumnDef("segment_row_id", "VARCHAR", True),
            ColumnDef("gvkey", "VARCHAR", True),
            ColumnDef("datadate", "DATE", True),
            ColumnDef("srcdate", "DATE"),
            ColumnDef("stype", "VARCHAR"),
            ColumnDef("sid", "VARCHAR"),
            ColumnDef("segment_type", "VARCHAR"),
            ColumnDef("segment_name", "VARCHAR"),
            ColumnDef("segment_name_secondary", "VARCHAR"),
            ColumnDef("curcds", "VARCHAR"),
            ColumnDef("revenue", "DOUBLE"),
            ColumnDef("sales", "DOUBLE"),
            ColumnDef("operating_income", "DOUBLE"),
            ColumnDef("operating_profit_before_dep", "DOUBLE"),
            ColumnDef("assets", "DOUBLE"),
            ColumnDef("capex", "DOUBLE"),
            ColumnDef("r_and_d", "DOUBLE"),
            ColumnDef("goodwill", "DOUBLE"),
            ColumnDef("employees", "DOUBLE"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("ingest_run_id", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("segment_row_id",),
    ),
    TableDef(
        name="wrds_compustat_quarterly_variant_metrics",
        columns=(
            ColumnDef("variant_row_id", "VARCHAR", True),
            ColumnDef("source_variant", "VARCHAR", True),
            ColumnDef("period_basis", "VARCHAR"),
            ColumnDef("provenance_class", "VARCHAR"),
            ColumnDef("gvkey", "VARCHAR", True),
            ColumnDef("iid", "VARCHAR"),
            ColumnDef("datadate", "DATE", True),
            ColumnDef("fiscal_year", "INTEGER"),
            ColumnDef("fiscal_quarter", "INTEGER"),
            ColumnDef("fyr", "INTEGER"),
            ColumnDef("indfmt", "VARCHAR"),
            ColumnDef("consol", "VARCHAR"),
            ColumnDef("popsrc", "VARCHAR"),
            ColumnDef("datafmt", "VARCHAR"),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("metric_name", "VARCHAR", True),
            ColumnDef("metric_value", "DOUBLE"),
            ColumnDef("metric_flag", "VARCHAR"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("ingest_run_id", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("variant_row_id",),
    ),
    TableDef(
        name="wrds_ibes_actuals_epsus",
        columns=(
            ColumnDef("actual_row_id", "VARCHAR", True),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("oftic", "VARCHAR"),
            ColumnDef("company_name", "VARCHAR"),
            ColumnDef("period_end", "DATE"),
            ColumnDef("measure", "VARCHAR"),
            ColumnDef("periodicity", "VARCHAR"),
            ColumnDef("announcement_date", "DATE"),
            ColumnDef("announcement_time", "VARCHAR"),
            ColumnDef("actual_date", "DATE"),
            ColumnDef("actual_time", "VARCHAR"),
            ColumnDef("actual_value", "DOUBLE"),
            ColumnDef("currency", "VARCHAR"),
            ColumnDef("usfirm", "INTEGER"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("ingest_run_id", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("actual_row_id",),
    ),
    TableDef(
        name="wrds_ibes_summary_epsus",
        columns=(
            ColumnDef("summary_row_id", "VARCHAR", True),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("oftic", "VARCHAR"),
            ColumnDef("company_name", "VARCHAR"),
            ColumnDef("statpers", "DATE"),
            ColumnDef("measure", "VARCHAR"),
            ColumnDef("fiscal_period", "VARCHAR"),
            ColumnDef("forecast_period_code", "VARCHAR"),
            ColumnDef("estimate_flag", "VARCHAR"),
            ColumnDef("currency", "VARCHAR"),
            ColumnDef("num_estimates", "INTEGER"),
            ColumnDef("num_up", "INTEGER"),
            ColumnDef("num_down", "INTEGER"),
            ColumnDef("median_estimate", "DOUBLE"),
            ColumnDef("mean_estimate", "DOUBLE"),
            ColumnDef("stdev_estimate", "DOUBLE"),
            ColumnDef("highest_estimate", "DOUBLE"),
            ColumnDef("lowest_estimate", "DOUBLE"),
            ColumnDef("usfirm", "INTEGER"),
            ColumnDef("period_end", "DATE"),
            ColumnDef("actual_value", "DOUBLE"),
            ColumnDef("actual_date", "DATE"),
            ColumnDef("announcement_date", "DATE"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("ingest_run_id", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("summary_row_id",),
    ),
    TableDef(
        name="wrds_source_access_registry",
        columns=(
            ColumnDef("source_key", "VARCHAR", True),
            ColumnDef("dataset_group", "VARCHAR"),
            ColumnDef("library_name", "VARCHAR"),
            ColumnDef("relation_name", "VARCHAR"),
            ColumnDef("access_status", "VARCHAR"),
            ColumnDef("notes", "VARCHAR"),
            ColumnDef("checked_at", "TIMESTAMPTZ"),
        ),
        primary_key=("source_key",),
    ),
    TableDef(
        name="wrds_ccm_link",
        columns=(
            ColumnDef("gvkey", "VARCHAR", True),
            ColumnDef("liid", "VARCHAR"),
            ColumnDef("lpermno", "BIGINT"),
            ColumnDef("lpermco", "BIGINT"),
            ColumnDef("linktype", "VARCHAR"),
            ColumnDef("linkprim", "VARCHAR"),
            ColumnDef("linkdt", "DATE"),
            ColumnDef("linkenddt", "DATE"),
            ColumnDef("usedflag", "INTEGER"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("ingest_run_id", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("gvkey", "liid", "lpermno", "linkdt"),
    ),
    TableDef(
        name="wrds_security_master",
        columns=(
            ColumnDef("permno", "BIGINT", True),
            ColumnDef("permco", "BIGINT"),
            ColumnDef("namedt", "DATE", True),
            ColumnDef("nameenddt", "DATE"),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("company_name", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("ncusip", "VARCHAR"),
            ColumnDef("shrcls", "VARCHAR"),
            ColumnDef("exchcd", "INTEGER"),
            ColumnDef("shrcd", "INTEGER"),
            ColumnDef("siccd", "INTEGER"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("ingest_run_id", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("permno", "namedt"),
    ),
    TableDef(
        name="wrds_company_master",
        columns=(
            ColumnDef("gvkey", "VARCHAR", True),
            ColumnDef("company_name", "VARCHAR"),
            ColumnDef("tic", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("sic", "VARCHAR"),
            ColumnDef("naics", "VARCHAR"),
            ColumnDef("fic", "VARCHAR"),
            ColumnDef("state_incorp", "VARCHAR"),
            ColumnDef("location_country", "VARCHAR"),
            ColumnDef("gsector", "VARCHAR"),
            ColumnDef("ggroup", "VARCHAR"),
            ColumnDef("gind", "VARCHAR"),
            ColumnDef("gsubind", "VARCHAR"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("ingest_run_id", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("gvkey",),
    ),
    TableDef(
        name="wrds_universe_membership_history",
        columns=(
            ColumnDef("membership_type", "VARCHAR", True),
            ColumnDef("membership_code", "VARCHAR", True),
            ColumnDef("membership_name", "VARCHAR"),
            ColumnDef("member_key", "VARCHAR", True),
            ColumnDef("source_kind", "VARCHAR", True),
            ColumnDef("permno", "BIGINT"),
            ColumnDef("permco", "BIGINT"),
            ColumnDef("gvkey", "VARCHAR"),
            ColumnDef("iid", "VARCHAR"),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("exchange_code", "INTEGER"),
            ColumnDef("effective_from", "DATE", True),
            ColumnDef("effective_to", "DATE"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("source_query_name", "VARCHAR"),
            ColumnDef("assumptions", "VARCHAR"),
            ColumnDef("ingest_run_id", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("membership_type", "membership_code", "member_key", "effective_from"),
    ),
    TableDef(
        name="wrds_ingest_runs",
        columns=(
            ColumnDef("run_id", "VARCHAR", True),
            ColumnDef("started_at", "TIMESTAMPTZ", True),
            ColumnDef("finished_at", "TIMESTAMPTZ"),
            ColumnDef("status", "VARCHAR"),
            ColumnDef("command_name", "VARCHAR"),
            ColumnDef("dataset_scope", "VARCHAR"),
            ColumnDef("sample_mode", "BOOLEAN"),
            ColumnDef("dry_run", "BOOLEAN"),
            ColumnDef("force", "BOOLEAN"),
            ColumnDef("config_json", "VARCHAR"),
            ColumnDef("summary_json", "VARCHAR"),
            ColumnDef("error_text", "VARCHAR"),
        ),
        primary_key=("run_id",),
    ),
    TableDef(
        name="wrds_ingest_checkpoints",
        columns=(
            ColumnDef("dataset_name", "VARCHAR", True),
            ColumnDef("chunk_key", "VARCHAR", True),
            ColumnDef("chunk_start", "DATE"),
            ColumnDef("chunk_end", "DATE"),
            ColumnDef("last_source_value", "VARCHAR"),
            ColumnDef("status", "VARCHAR"),
            ColumnDef("rows_fetched", "BIGINT"),
            ColumnDef("rows_written", "BIGINT"),
            ColumnDef("run_id", "VARCHAR"),
            ColumnDef("updated_at", "TIMESTAMPTZ"),
            ColumnDef("notes", "VARCHAR"),
        ),
        primary_key=("dataset_name", "chunk_key"),
    ),
)

CANONICAL_TABLES: tuple[TableDef, ...] = (
    TableDef(
        name="entity_master",
        columns=(
            ColumnDef("entity_id", "VARCHAR", True),
            ColumnDef("gvkey", "VARCHAR"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("company_name", "VARCHAR"),
            ColumnDef("current_ticker", "VARCHAR"),
            ColumnDef("current_cusip", "VARCHAR"),
            ColumnDef("sic", "VARCHAR"),
            ColumnDef("naics", "VARCHAR"),
            ColumnDef("gsector", "VARCHAR"),
            ColumnDef("ggroup", "VARCHAR"),
            ColumnDef("gind", "VARCHAR"),
            ColumnDef("gsubind", "VARCHAR"),
            ColumnDef("incorp_country", "VARCHAR"),
            ColumnDef("incorp_state", "VARCHAR"),
            ColumnDef("first_seen_date", "DATE"),
            ColumnDef("last_seen_date", "DATE"),
            ColumnDef("permno_count", "BIGINT"),
            ColumnDef("permco_count", "BIGINT"),
            ColumnDef("source_summary", "VARCHAR"),
            ColumnDef("refreshed_at", "TIMESTAMPTZ"),
        ),
        primary_key=("entity_id",),
    ),
    TableDef(
        name="security_link_history",
        columns=(
            ColumnDef("link_id", "VARCHAR", True),
            ColumnDef("gvkey", "VARCHAR"),
            ColumnDef("iid", "VARCHAR"),
            ColumnDef("permno", "BIGINT"),
            ColumnDef("permco", "BIGINT"),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("exchange_code", "INTEGER"),
            ColumnDef("share_code", "INTEGER"),
            ColumnDef("security_name", "VARCHAR"),
            ColumnDef("link_type", "VARCHAR"),
            ColumnDef("link_primary", "VARCHAR"),
            ColumnDef("effective_from", "DATE"),
            ColumnDef("effective_to", "DATE"),
            ColumnDef("source_summary", "VARCHAR"),
            ColumnDef("refreshed_at", "TIMESTAMPTZ"),
        ),
        primary_key=("link_id",),
    ),
    TableDef(
        name="prices_daily_canonical",
        columns=(
            ColumnDef("trade_date", "DATE", True),
            ColumnDef("available_date", "DATE"),
            ColumnDef("permno", "BIGINT", True),
            ColumnDef("permco", "BIGINT"),
            ColumnDef("gvkey", "VARCHAR"),
            ColumnDef("iid", "VARCHAR"),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("exchange_code", "INTEGER"),
            ColumnDef("close_price", "DOUBLE"),
            ColumnDef("return_total", "DOUBLE"),
            ColumnDef("return_ex_dividend", "DOUBLE"),
            ColumnDef("shares_outstanding", "DOUBLE"),
            ColumnDef("market_cap", "DOUBLE"),
            ColumnDef("price_adjust_factor", "DOUBLE"),
            ColumnDef("share_adjust_factor", "DOUBLE"),
            ColumnDef("delist_code", "INTEGER"),
            ColumnDef("delist_date", "DATE"),
            ColumnDef("delist_return", "DOUBLE"),
            ColumnDef("delist_return_ex_dividend", "DOUBLE"),
            ColumnDef("delist_price", "DOUBLE"),
            ColumnDef("source_table", "VARCHAR"),
            ColumnDef("refreshed_at", "TIMESTAMPTZ"),
        ),
        primary_key=("permno", "trade_date"),
    ),
    TableDef(
        name="financials_quarterly_canonical",
        columns=(
            ColumnDef("gvkey", "VARCHAR", True),
            ColumnDef("period_end", "DATE", True),
            ColumnDef("available_date", "DATE"),
            ColumnDef("fiscal_year", "INTEGER"),
            ColumnDef("fiscal_quarter", "INTEGER"),
            ColumnDef("currency", "VARCHAR"),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("revenue", "DOUBLE"),
            ColumnDef("cogs", "DOUBLE"),
            ColumnDef("gross_profit", "DOUBLE"),
            ColumnDef("sga", "DOUBLE"),
            ColumnDef("operating_income", "DOUBLE"),
            ColumnDef("pretax_income", "DOUBLE"),
            ColumnDef("tax", "DOUBLE"),
            ColumnDef("net_income", "DOUBLE"),
            ColumnDef("net_income_common", "DOUBLE"),
            ColumnDef("interest", "DOUBLE"),
            ColumnDef("d_and_a", "DOUBLE"),
            ColumnDef("eps_basic", "DOUBLE"),
            ColumnDef("eps_diluted", "DOUBLE"),
            ColumnDef("shares_basic", "DOUBLE"),
            ColumnDef("shares_diluted", "DOUBLE"),
            ColumnDef("assets", "DOUBLE"),
            ColumnDef("liabilities", "DOUBLE"),
            ColumnDef("equity", "DOUBLE"),
            ColumnDef("current_assets", "DOUBLE"),
            ColumnDef("current_liabilities", "DOUBLE"),
            ColumnDef("cash", "DOUBLE"),
            ColumnDef("current_fin_assets", "DOUBLE"),
            ColumnDef("non_current_fin_assets", "DOUBLE"),
            ColumnDef("current_fin_liabilities", "DOUBLE"),
            ColumnDef("non_current_fin_liabilities", "DOUBLE"),
            ColumnDef("debt_short", "DOUBLE"),
            ColumnDef("debt_long", "DOUBLE"),
            ColumnDef("accounts_receivable", "DOUBLE"),
            ColumnDef("inventory", "DOUBLE"),
            ColumnDef("accounts_payable", "DOUBLE"),
            ColumnDef("deferred_revenue", "DOUBLE"),
            ColumnDef("goodwill", "DOUBLE"),
            ColumnDef("intangibles", "DOUBLE"),
            ColumnDef("common_stock", "DOUBLE"),
            ColumnDef("retained_earnings", "DOUBLE"),
            ColumnDef("aoci", "DOUBLE"),
            ColumnDef("amortization", "DOUBLE"),
            ColumnDef("operating_cash_flow", "DOUBLE"),
            ColumnDef("investing_cash_flow", "DOUBLE"),
            ColumnDef("financing_cash_flow", "DOUBLE"),
            ColumnDef("capital_expenditure", "DOUBLE"),
            ColumnDef("dividends", "DOUBLE"),
            ColumnDef("dividends_paid", "DOUBLE"),
            ColumnDef("repurchases", "DOUBLE"),
            ColumnDef("price_period_end", "DOUBLE"),
            ColumnDef("source_table", "VARCHAR"),
            ColumnDef("refreshed_at", "TIMESTAMPTZ"),
        ),
        primary_key=("gvkey", "period_end", "fiscal_year", "fiscal_quarter"),
    ),
    TableDef(
        name="financials_annual_canonical",
        columns=(
            ColumnDef("gvkey", "VARCHAR", True),
            ColumnDef("period_end", "DATE", True),
            ColumnDef("available_date", "DATE"),
            ColumnDef("fiscal_year", "INTEGER"),
            ColumnDef("currency", "VARCHAR"),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("revenue", "DOUBLE"),
            ColumnDef("cogs", "DOUBLE"),
            ColumnDef("gross_profit", "DOUBLE"),
            ColumnDef("sga", "DOUBLE"),
            ColumnDef("operating_income", "DOUBLE"),
            ColumnDef("pretax_income", "DOUBLE"),
            ColumnDef("tax", "DOUBLE"),
            ColumnDef("net_income", "DOUBLE"),
            ColumnDef("net_income_common", "DOUBLE"),
            ColumnDef("interest", "DOUBLE"),
            ColumnDef("d_and_a", "DOUBLE"),
            ColumnDef("eps_basic", "DOUBLE"),
            ColumnDef("eps_diluted", "DOUBLE"),
            ColumnDef("shares_outstanding", "DOUBLE"),
            ColumnDef("assets", "DOUBLE"),
            ColumnDef("liabilities", "DOUBLE"),
            ColumnDef("equity", "DOUBLE"),
            ColumnDef("current_assets", "DOUBLE"),
            ColumnDef("current_liabilities", "DOUBLE"),
            ColumnDef("cash", "DOUBLE"),
            ColumnDef("current_fin_assets", "DOUBLE"),
            ColumnDef("non_current_fin_assets", "DOUBLE"),
            ColumnDef("current_fin_liabilities", "DOUBLE"),
            ColumnDef("non_current_fin_liabilities", "DOUBLE"),
            ColumnDef("debt_short", "DOUBLE"),
            ColumnDef("debt_long", "DOUBLE"),
            ColumnDef("accounts_receivable", "DOUBLE"),
            ColumnDef("inventory", "DOUBLE"),
            ColumnDef("accounts_payable", "DOUBLE"),
            ColumnDef("deferred_revenue", "DOUBLE"),
            ColumnDef("goodwill", "DOUBLE"),
            ColumnDef("intangibles", "DOUBLE"),
            ColumnDef("common_stock", "DOUBLE"),
            ColumnDef("retained_earnings", "DOUBLE"),
            ColumnDef("aoci", "DOUBLE"),
            ColumnDef("amortization", "DOUBLE"),
            ColumnDef("operating_cash_flow", "DOUBLE"),
            ColumnDef("investing_cash_flow", "DOUBLE"),
            ColumnDef("financing_cash_flow", "DOUBLE"),
            ColumnDef("capital_expenditure", "DOUBLE"),
            ColumnDef("dividends", "DOUBLE"),
            ColumnDef("dividends_paid", "DOUBLE"),
            ColumnDef("repurchases", "DOUBLE"),
            ColumnDef("price_period_end", "DOUBLE"),
            ColumnDef("source_table", "VARCHAR"),
            ColumnDef("refreshed_at", "TIMESTAMPTZ"),
        ),
        primary_key=("gvkey", "period_end"),
    ),
    TableDef(
        name="segments_historical_canonical",
        columns=(
            ColumnDef("segment_row_id", "VARCHAR", True),
            ColumnDef("gvkey", "VARCHAR"),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("period_end", "DATE"),
            ColumnDef("available_date", "DATE"),
            ColumnDef("segment_type", "VARCHAR"),
            ColumnDef("segment_key", "VARCHAR"),
            ColumnDef("segment_name", "VARCHAR"),
            ColumnDef("segment_name_secondary", "VARCHAR"),
            ColumnDef("currency", "VARCHAR"),
            ColumnDef("revenue", "DOUBLE"),
            ColumnDef("sales", "DOUBLE"),
            ColumnDef("operating_income", "DOUBLE"),
            ColumnDef("operating_profit_before_dep", "DOUBLE"),
            ColumnDef("assets", "DOUBLE"),
            ColumnDef("capex", "DOUBLE"),
            ColumnDef("r_and_d", "DOUBLE"),
            ColumnDef("goodwill", "DOUBLE"),
            ColumnDef("employees", "DOUBLE"),
            ColumnDef("source_table", "VARCHAR"),
            ColumnDef("refreshed_at", "TIMESTAMPTZ"),
        ),
        primary_key=("segment_row_id",),
    ),
    TableDef(
        name="universe_membership_history",
        columns=(
            ColumnDef("membership_type", "VARCHAR", True),
            ColumnDef("membership_code", "VARCHAR", True),
            ColumnDef("membership_name", "VARCHAR"),
            ColumnDef("member_key", "VARCHAR", True),
            ColumnDef("permno", "BIGINT"),
            ColumnDef("permco", "BIGINT"),
            ColumnDef("gvkey", "VARCHAR"),
            ColumnDef("iid", "VARCHAR"),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("effective_from", "DATE", True),
            ColumnDef("effective_to", "DATE"),
            ColumnDef("source_kind", "VARCHAR"),
            ColumnDef("source_summary", "VARCHAR"),
            ColumnDef("refreshed_at", "TIMESTAMPTZ"),
        ),
        primary_key=("membership_type", "membership_code", "member_key", "effective_from"),
    ),
)

VALIDATION_TABLES: tuple[TableDef, ...] = (
    TableDef(
        name="metric_mapping_registry",
        columns=(
            ColumnDef("canonical_metric_name", "VARCHAR", True),
            ColumnDef("statement_type", "VARCHAR", True),
            ColumnDef("metric_class", "VARCHAR"),
            ColumnDef("value_mode_default", "VARCHAR"),
            ColumnDef("reported_value_policy", "VARCHAR"),
            ColumnDef("normalized_value_policy", "VARCHAR"),
            ColumnDef("scope_rule", "VARCHAR"),
            ColumnDef("mismatch_policy", "VARCHAR"),
            ColumnDef("wrds_table_name", "VARCHAR", True),
            ColumnDef("wrds_column_name", "VARCHAR", True),
            ColumnDef("sec_table_name", "VARCHAR", True),
            ColumnDef("sec_column_name", "VARCHAR"),
            ColumnDef("sec_extra_column_name", "VARCHAR"),
            ColumnDef("comparison_rule", "VARCHAR"),
            ColumnDef("tolerance_type", "VARCHAR"),
            ColumnDef("tolerance_value", "DOUBLE"),
            ColumnDef("value_scale_rule", "VARCHAR"),
            ColumnDef("sign_rule", "VARCHAR"),
            ColumnDef("post_2012_mode", "VARCHAR"),
            ColumnDef("pre_2012_mode", "VARCHAR"),
            ColumnDef("pre_2012_supported_flag", "BOOLEAN"),
            ColumnDef("pre_2012_value_mode_default", "VARCHAR"),
            ColumnDef("pre_2012_tolerance_override", "DOUBLE"),
            ColumnDef("pre_2012_known_gap_policy", "VARCHAR"),
            ColumnDef("known_gap_flag", "BOOLEAN"),
            ColumnDef("known_gap_reason", "VARCHAR"),
            ColumnDef("recommended_compare_mode", "VARCHAR"),
            ColumnDef("notes", "VARCHAR"),
            ColumnDef("is_active", "BOOLEAN"),
            ColumnDef("updated_at", "TIMESTAMPTZ"),
        ),
        primary_key=("canonical_metric_name", "statement_type"),
    ),
    TableDef(
        name="validation_sec_vs_wrds_financials",
        columns=(
            ColumnDef("result_id", "VARCHAR", True),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("market", "VARCHAR"),
            ColumnDef("gvkey", "VARCHAR"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("period_end", "DATE"),
            ColumnDef("wrds_period_end", "DATE"),
            ColumnDef("sec_period_end", "DATE"),
            ColumnDef("period_end_delta_days", "INTEGER"),
            ColumnDef("fiscal_year", "INTEGER"),
            ColumnDef("fiscal_quarter", "INTEGER"),
            ColumnDef("statement_type", "VARCHAR"),
            ColumnDef("metric_name", "VARCHAR"),
            ColumnDef("compare_mode", "VARCHAR"),
            ColumnDef("value_mode_used", "VARCHAR"),
            ColumnDef("metric_class", "VARCHAR"),
            ColumnDef("scope_rule", "VARCHAR"),
            ColumnDef("supported_in_time_regime", "BOOLEAN"),
            ColumnDef("effective_tolerance_value", "DOUBLE"),
            ColumnDef("wrds_value", "DOUBLE"),
            ColumnDef("reported_sec_value", "DOUBLE"),
            ColumnDef("normalized_sec_value", "DOUBLE"),
            ColumnDef("sec_value", "DOUBLE"),
            ColumnDef("abs_diff", "DOUBLE"),
            ColumnDef("pct_diff", "DOUBLE"),
            ColumnDef("missing_on_wrds", "BOOLEAN"),
            ColumnDef("missing_on_sec", "BOOLEAN"),
            ColumnDef("sign_mismatch", "BOOLEAN"),
            ColumnDef("tolerance_breach", "BOOLEAN"),
            ColumnDef("sec_filing_date", "DATE"),
            ColumnDef("sec_available_date", "DATE"),
            ColumnDef("comparison_status", "VARCHAR"),
            ColumnDef("mismatch_class", "VARCHAR"),
            ColumnDef("semantic_gap_class", "VARCHAR"),
            ColumnDef("time_regime", "VARCHAR"),
            ColumnDef("reference_db_path", "VARCHAR"),
            ColumnDef("reference_source_kind", "VARCHAR"),
            ColumnDef("identifier_linkage_basis", "VARCHAR"),
            ColumnDef("identifier_gap", "BOOLEAN"),
            ColumnDef("pit_mismatch", "BOOLEAN"),
            ColumnDef("diagnostic_code", "VARCHAR"),
            ColumnDef("notes", "VARCHAR"),
            ColumnDef("wrds_row_count", "INTEGER"),
            ColumnDef("sec_row_count", "INTEGER"),
            ColumnDef("comparison_run_id", "VARCHAR"),
            ColumnDef("created_at", "TIMESTAMPTZ"),
        ),
        primary_key=("result_id",),
    ),
    TableDef(
        name="segment_metric_policy_registry",
        columns=(
            ColumnDef("metric_name", "VARCHAR", True),
            ColumnDef("statement_type", "VARCHAR", True),
            ColumnDef("compare_pair", "VARCHAR"),
            ColumnDef("metric_class", "VARCHAR"),
            ColumnDef("value_mode_default", "VARCHAR"),
            ColumnDef("dimension_normalization_rule", "VARCHAR"),
            ColumnDef("member_normalization_rule", "VARCHAR"),
            ColumnDef("reported_value_policy", "VARCHAR"),
            ColumnDef("normalized_value_policy", "VARCHAR"),
            ColumnDef("mismatch_policy", "VARCHAR"),
            ColumnDef("tolerance_type", "VARCHAR"),
            ColumnDef("tolerance_value", "DOUBLE"),
            ColumnDef("known_gap_flag", "BOOLEAN"),
            ColumnDef("known_gap_reason", "VARCHAR"),
            ColumnDef("recommended_compare_mode", "VARCHAR"),
            ColumnDef("notes", "VARCHAR"),
            ColumnDef("is_active", "BOOLEAN"),
            ColumnDef("updated_at", "TIMESTAMPTZ"),
        ),
        primary_key=("metric_name", "statement_type"),
    ),
    TableDef(
        name="segment_cluster_policy_registry",
        columns=(
            ColumnDef("issuer_cluster", "VARCHAR", True),
            ColumnDef("source_lane", "VARCHAR"),
            ColumnDef("companyfacts_required", "BOOLEAN"),
            ColumnDef("filing_only_validated_allowed", "BOOLEAN"),
            ColumnDef("revenue_supported", "BOOLEAN"),
            ColumnDef("operating_income_supported", "BOOLEAN"),
            ColumnDef("preferred_segment_types", "VARCHAR"),
            ColumnDef("source_coverage_policy", "VARCHAR"),
            ColumnDef("mismatch_policy", "VARCHAR"),
            ColumnDef("low_confidence_flag", "BOOLEAN"),
            ColumnDef("recovery_policy", "VARCHAR"),
            ColumnDef("notes", "VARCHAR"),
            ColumnDef("is_active", "BOOLEAN"),
            ColumnDef("updated_at", "TIMESTAMPTZ"),
        ),
        primary_key=("issuer_cluster",),
    ),
    TableDef(
        name="segment_issuer_source_coverage",
        columns=(
            ColumnDef("coverage_result_id", "VARCHAR", True),
            ColumnDef("survey_run_id", "VARCHAR"),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("market", "VARCHAR"),
            ColumnDef("start_date", "DATE"),
            ColumnDef("companyfacts_rows", "INTEGER"),
            ColumnDef("filing_rows", "INTEGER"),
            ColumnDef("companyfacts_periods", "INTEGER"),
            ColumnDef("filing_periods", "INTEGER"),
            ColumnDef("overlap_periods", "INTEGER"),
            ColumnDef("companyfacts_revenue_periods", "INTEGER"),
            ColumnDef("companyfacts_operating_income_periods", "INTEGER"),
            ColumnDef("filing_revenue_periods", "INTEGER"),
            ColumnDef("filing_operating_income_periods", "INTEGER"),
            ColumnDef("business_rows", "INTEGER"),
            ColumnDef("geography_rows", "INTEGER"),
            ColumnDef("product_rows", "INTEGER"),
            ColumnDef("other_rows", "INTEGER"),
            ColumnDef("distinct_segment_keys", "INTEGER"),
            ColumnDef("filing_source_count", "INTEGER"),
            ColumnDef("ixbrl_rows", "INTEGER"),
            ColumnDef("xbrl_instance_rows", "INTEGER"),
            ColumnDef("html_table_rows", "INTEGER"),
            ColumnDef("ixbrl_revenue_periods", "INTEGER"),
            ColumnDef("ixbrl_operating_income_periods", "INTEGER"),
            ColumnDef("xbrl_instance_revenue_periods", "INTEGER"),
            ColumnDef("xbrl_instance_operating_income_periods", "INTEGER"),
            ColumnDef("html_table_revenue_periods", "INTEGER"),
            ColumnDef("html_table_operating_income_periods", "INTEGER"),
            ColumnDef("high_confidence_rows", "INTEGER"),
            ColumnDef("medium_confidence_rows", "INTEGER"),
            ColumnDef("low_confidence_rows", "INTEGER"),
            ColumnDef("filing_meta_count", "INTEGER"),
            ColumnDef("filing_10q_count", "INTEGER"),
            ColumnDef("filing_10k_count", "INTEGER"),
            ColumnDef("best_source_name", "VARCHAR"),
            ColumnDef("best_source_rank", "INTEGER"),
            ColumnDef("consistency_score", "DOUBLE"),
            ColumnDef("confidence_score", "DOUBLE"),
            ColumnDef("confidence_band", "VARCHAR"),
            ColumnDef("confidence_reason", "VARCHAR"),
            ColumnDef("source_cluster", "VARCHAR"),
            ColumnDef("metric_cluster", "VARCHAR"),
            ColumnDef("segment_type_profile", "VARCHAR"),
            ColumnDef("issuer_cluster", "VARCHAR"),
            ColumnDef("issuer_cluster_detail", "VARCHAR"),
            ColumnDef("source_lane", "VARCHAR"),
            ColumnDef("coverage_reason", "VARCHAR"),
            ColumnDef("source_poor_reason", "VARCHAR"),
            ColumnDef("source_poor_reason_detail", "VARCHAR"),
            ColumnDef("parser_candidate_flag", "BOOLEAN"),
            ColumnDef("recovery_bucket", "VARCHAR"),
            ColumnDef("recoverability_class", "VARCHAR"),
            ColumnDef("recovery_score", "DOUBLE"),
            ColumnDef("recovery_reason", "VARCHAR"),
            ColumnDef("recommended_action", "VARCHAR"),
            ColumnDef("fetch_required", "BOOLEAN"),
            ColumnDef("target_source", "VARCHAR"),
            ColumnDef("expected_gain", "VARCHAR"),
            ColumnDef("priority_rank", "INTEGER"),
            ColumnDef("recovery_confidence", "VARCHAR"),
            ColumnDef("cache_presence_detail", "VARCHAR"),
            ColumnDef("filing_meta_strength", "VARCHAR"),
            ColumnDef("source_signal_strength", "VARCHAR"),
            ColumnDef("companyfacts_available", "BOOLEAN"),
            ColumnDef("filing_available", "BOOLEAN"),
            ColumnDef("overlap_available", "BOOLEAN"),
            ColumnDef("filing_only_validated_candidate", "BOOLEAN"),
            ColumnDef("created_at", "TIMESTAMPTZ"),
        ),
        primary_key=("coverage_result_id",),
    ),
    TableDef(
        name="segment_recovery_candidate_registry",
        columns=(
            ColumnDef("candidate_result_id", "VARCHAR", True),
            ColumnDef("survey_run_id", "VARCHAR"),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("market", "VARCHAR"),
            ColumnDef("issuer_cluster", "VARCHAR"),
            ColumnDef("issuer_cluster_detail", "VARCHAR"),
            ColumnDef("source_poor_reason", "VARCHAR"),
            ColumnDef("confidence_score", "DOUBLE"),
            ColumnDef("confidence_band", "VARCHAR"),
            ColumnDef("recovery_bucket", "VARCHAR"),
            ColumnDef("recoverability_class", "VARCHAR"),
            ColumnDef("recovery_score", "DOUBLE"),
            ColumnDef("recovery_reason", "VARCHAR"),
            ColumnDef("recommended_action", "VARCHAR"),
            ColumnDef("target_source", "VARCHAR"),
            ColumnDef("fetch_required", "BOOLEAN"),
            ColumnDef("expected_gain", "VARCHAR"),
            ColumnDef("priority_rank", "INTEGER"),
            ColumnDef("recovery_confidence", "VARCHAR"),
            ColumnDef("cache_presence_detail", "VARCHAR"),
            ColumnDef("filing_meta_strength", "VARCHAR"),
            ColumnDef("source_signal_strength", "VARCHAR"),
            ColumnDef("filing_meta_count", "INTEGER"),
            ColumnDef("filing_10q_count", "INTEGER"),
            ColumnDef("filing_10k_count", "INTEGER"),
            ColumnDef("parser_candidate_flag", "BOOLEAN"),
            ColumnDef("created_at", "TIMESTAMPTZ"),
        ),
        primary_key=("candidate_result_id",),
    ),
    TableDef(
        name="wrds_aux_metric_readiness_summary",
        columns=(
            ColumnDef("readiness_result_id", "VARCHAR", True),
            ColumnDef("survey_run_id", "VARCHAR"),
            ColumnDef("metric_name", "VARCHAR"),
            ColumnDef("statement_type", "VARCHAR"),
            ColumnDef("wrds_reference_candidate", "VARCHAR"),
            ColumnDef("wrds_reference_table", "VARCHAR"),
            ColumnDef("wrds_reference_column", "VARCHAR"),
            ColumnDef("candidate_row_count", "INTEGER"),
            ColumnDef("candidate_issuer_count", "INTEGER"),
            ColumnDef("candidate_non_null_rows", "INTEGER"),
            ColumnDef("candidate_non_null_issuers", "INTEGER"),
            ColumnDef("sec_base_non_null_rows", "INTEGER"),
            ColumnDef("sec_base_non_null_issuers", "INTEGER"),
            ColumnDef("sec_extra_non_null_rows", "INTEGER"),
            ColumnDef("sec_extra_non_null_issuers", "INTEGER"),
            ColumnDef("sec_raw_non_null_rows", "INTEGER"),
            ColumnDef("sec_raw_non_null_issuers", "INTEGER"),
            ColumnDef("candidate_overlap_rows", "INTEGER"),
            ColumnDef("candidate_overlap_issuers", "INTEGER"),
            ColumnDef("coverage_start_date", "DATE"),
            ColumnDef("coverage_end_date", "DATE"),
            ColumnDef("coverage_note", "VARCHAR"),
            ColumnDef("blocker_type", "VARCHAR"),
            ColumnDef("blocker_reason", "VARCHAR"),
            ColumnDef("readiness_class", "VARCHAR"),
            ColumnDef("pilot_compare_ready", "BOOLEAN"),
            ColumnDef("recommended_next_action", "VARCHAR"),
            ColumnDef("created_at", "TIMESTAMPTZ"),
        ),
        primary_key=("readiness_result_id",),
    ),
    TableDef(
        name="validation_sec_segment_quality",
        columns=(
            ColumnDef("result_id", "VARCHAR", True),
            ColumnDef("ticker", "VARCHAR"),
            ColumnDef("market", "VARCHAR"),
            ColumnDef("period_end", "DATE"),
            ColumnDef("statement_type", "VARCHAR"),
            ColumnDef("metric_name", "VARCHAR"),
            ColumnDef("issuer_cluster", "VARCHAR"),
            ColumnDef("source_cluster", "VARCHAR"),
            ColumnDef("metric_cluster", "VARCHAR"),
            ColumnDef("segment_type_profile", "VARCHAR"),
            ColumnDef("source_lane", "VARCHAR"),
            ColumnDef("issuer_cluster_detail", "VARCHAR"),
            ColumnDef("coverage_reason", "VARCHAR"),
            ColumnDef("companyfacts_available", "BOOLEAN"),
            ColumnDef("filing_available", "BOOLEAN"),
            ColumnDef("overlap_available", "BOOLEAN"),
            ColumnDef("segment_type_companyfacts", "VARCHAR"),
            ColumnDef("segment_type_filing", "VARCHAR"),
            ColumnDef("segment_type_normalized", "VARCHAR"),
            ColumnDef("segment_name_companyfacts", "VARCHAR"),
            ColumnDef("segment_name_filing", "VARCHAR"),
            ColumnDef("segment_name_normalized", "VARCHAR"),
            ColumnDef("companyfacts_value", "DOUBLE"),
            ColumnDef("filing_value", "DOUBLE"),
            ColumnDef("abs_diff", "DOUBLE"),
            ColumnDef("pct_diff", "DOUBLE"),
            ColumnDef("missing_on_companyfacts", "BOOLEAN"),
            ColumnDef("missing_on_filing", "BOOLEAN"),
            ColumnDef("comparison_status", "VARCHAR"),
            ColumnDef("mismatch_class", "VARCHAR"),
            ColumnDef("semantic_gap_class", "VARCHAR"),
            ColumnDef("companyfacts_source", "VARCHAR"),
            ColumnDef("filing_source", "VARCHAR"),
            ColumnDef("filing_source_confidence", "VARCHAR"),
            ColumnDef("filing_source_rank", "INTEGER"),
            ColumnDef("issuer_confidence_score", "DOUBLE"),
            ColumnDef("issuer_confidence_band", "VARCHAR"),
            ColumnDef("companyfacts_available_date", "DATE"),
            ColumnDef("filing_available_date", "DATE"),
            ColumnDef("filing_accession", "VARCHAR"),
            ColumnDef("companyfacts_row_count", "INTEGER"),
            ColumnDef("filing_row_count", "INTEGER"),
            ColumnDef("compare_mode", "VARCHAR"),
            ColumnDef("value_mode_used", "VARCHAR"),
            ColumnDef("diagnostic_code", "VARCHAR"),
            ColumnDef("notes", "VARCHAR"),
            ColumnDef("comparison_run_id", "VARCHAR"),
            ColumnDef("created_at", "TIMESTAMPTZ"),
        ),
        primary_key=("result_id",),
    ),
)

KR_LAKE_TABLES: tuple[TableDef, ...] = (
    TableDef(
        name="kr_company_master",
        columns=(
            ColumnDef("company_key", "VARCHAR", True),
            ColumnDef("gvkey", "VARCHAR", True),
            ColumnDef("iid", "VARCHAR"),
            ColumnDef("company_name", "VARCHAR"),
            ColumnDef("company_name_long", "VARCHAR"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("fic", "VARCHAR"),
            ColumnDef("loc", "VARCHAR"),
            ColumnDef("ticker_raw", "VARCHAR"),
            ColumnDef("ibtic", "VARCHAR"),
            ColumnDef("cusip", "VARCHAR"),
            ColumnDef("isin", "VARCHAR"),
            ColumnDef("local_code_6", "VARCHAR"),
            ColumnDef("exchange_code", "INTEGER"),
            ColumnDef("exchange_desc", "VARCHAR"),
            ColumnDef("exchange_country", "VARCHAR"),
            ColumnDef("market_tier", "VARCHAR"),
            ColumnDef("company_status", "VARCHAR"),
            ColumnDef("security_status", "VARCHAR"),
            ColumnDef("active_flag", "BOOLEAN"),
            ColumnDef("gsector", "VARCHAR"),
            ColumnDef("gind", "VARCHAR"),
            ColumnDef("gsubind", "VARCHAR"),
            ColumnDef("sic", "VARCHAR"),
            ColumnDef("naics", "VARCHAR"),
            ColumnDef("stko", "VARCHAR"),
            ColumnDef("prirow", "VARCHAR"),
            ColumnDef("ipodate", "DATE"),
            ColumnDef("dldte", "DATE"),
            ColumnDef("dldtei", "DATE"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("company_key",),
    ),
    TableDef(
        name="kr_financials_annual_canonical",
        columns=(
            ColumnDef("row_id", "VARCHAR", True),
            ColumnDef("gvkey", "VARCHAR", True),
            ColumnDef("iid", "VARCHAR"),
            ColumnDef("company_key", "VARCHAR"),
            ColumnDef("period_end", "DATE", True),
            ColumnDef("available_date", "DATE"),
            ColumnDef("filing_date", "DATE"),
            ColumnDef("fiscal_year", "INTEGER"),
            ColumnDef("fiscal_year_end_month", "INTEGER"),
            ColumnDef("currency_code", "VARCHAR"),
            ColumnDef("indfmt", "VARCHAR"),
            ColumnDef("consol", "VARCHAR"),
            ColumnDef("popsrc", "VARCHAR"),
            ColumnDef("datafmt", "VARCHAR"),
            ColumnDef("final_flag", "VARCHAR"),
            ColumnDef("update_code", "VARCHAR"),
            ColumnDef("source_code", "VARCHAR"),
            ColumnDef("ticker_raw", "VARCHAR"),
            ColumnDef("ibtic", "VARCHAR"),
            ColumnDef("isin", "VARCHAR"),
            ColumnDef("local_code_6", "VARCHAR"),
            ColumnDef("market_tier", "VARCHAR"),
            ColumnDef("exchange_code", "INTEGER"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("revenue", "DOUBLE"),
            ColumnDef("gross_profit", "DOUBLE"),
            ColumnDef("operating_income", "DOUBLE"),
            ColumnDef("pretax_income", "DOUBLE"),
            ColumnDef("tax", "DOUBLE"),
            ColumnDef("net_income", "DOUBLE"),
            ColumnDef("operating_cash_flow", "DOUBLE"),
            ColumnDef("capex", "DOUBLE"),
            ColumnDef("cash", "DOUBLE"),
            ColumnDef("receivables", "DOUBLE"),
            ColumnDef("inventory", "DOUBLE"),
            ColumnDef("current_assets", "DOUBLE"),
            ColumnDef("non_current_assets", "DOUBLE"),
            ColumnDef("current_liabilities", "DOUBLE"),
            ColumnDef("non_current_liabilities", "DOUBLE"),
            ColumnDef("total_assets", "DOUBLE"),
            ColumnDef("total_liabilities", "DOUBLE"),
            ColumnDef("equity", "DOUBLE"),
            ColumnDef("retained_earnings", "DOUBLE"),
            ColumnDef("common_stock", "DOUBLE"),
            ColumnDef("r_and_d", "DOUBLE"),
            ColumnDef("d_and_a", "DOUBLE"),
            ColumnDef("interest", "DOUBLE"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("row_id",),
    ),
    TableDef(
        name="kr_financials_quarterly_canonical",
        columns=(
            ColumnDef("row_id", "VARCHAR", True),
            ColumnDef("gvkey", "VARCHAR", True),
            ColumnDef("iid", "VARCHAR"),
            ColumnDef("company_key", "VARCHAR"),
            ColumnDef("period_end", "DATE", True),
            ColumnDef("available_date", "DATE"),
            ColumnDef("filing_date", "DATE"),
            ColumnDef("fiscal_year", "INTEGER"),
            ColumnDef("fiscal_quarter", "INTEGER"),
            ColumnDef("fiscal_year_end_month", "INTEGER"),
            ColumnDef("currency_code", "VARCHAR"),
            ColumnDef("indfmt", "VARCHAR"),
            ColumnDef("consol", "VARCHAR"),
            ColumnDef("popsrc", "VARCHAR"),
            ColumnDef("datafmt", "VARCHAR"),
            ColumnDef("update_code", "VARCHAR"),
            ColumnDef("source_code", "VARCHAR"),
            ColumnDef("ticker_raw", "VARCHAR"),
            ColumnDef("ibtic", "VARCHAR"),
            ColumnDef("isin", "VARCHAR"),
            ColumnDef("local_code_6", "VARCHAR"),
            ColumnDef("market_tier", "VARCHAR"),
            ColumnDef("exchange_code", "INTEGER"),
            ColumnDef("cik", "VARCHAR"),
            ColumnDef("revenue", "DOUBLE"),
            ColumnDef("gross_profit", "DOUBLE"),
            ColumnDef("operating_income", "DOUBLE"),
            ColumnDef("pretax_income", "DOUBLE"),
            ColumnDef("tax", "DOUBLE"),
            ColumnDef("net_income", "DOUBLE"),
            ColumnDef("operating_cash_flow", "DOUBLE"),
            ColumnDef("capex", "DOUBLE"),
            ColumnDef("cash", "DOUBLE"),
            ColumnDef("receivables", "DOUBLE"),
            ColumnDef("inventory", "DOUBLE"),
            ColumnDef("current_assets", "DOUBLE"),
            ColumnDef("non_current_assets", "DOUBLE"),
            ColumnDef("current_liabilities", "DOUBLE"),
            ColumnDef("non_current_liabilities", "DOUBLE"),
            ColumnDef("total_assets", "DOUBLE"),
            ColumnDef("total_liabilities", "DOUBLE"),
            ColumnDef("equity", "DOUBLE"),
            ColumnDef("retained_earnings", "DOUBLE"),
            ColumnDef("common_stock", "DOUBLE"),
            ColumnDef("r_and_d", "DOUBLE"),
            ColumnDef("d_and_a", "DOUBLE"),
            ColumnDef("interest", "DOUBLE"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("row_id",),
    ),
    TableDef(
        name="kr_security_status_history",
        columns=(
            ColumnDef("status_row_id", "VARCHAR", True),
            ColumnDef("gvkey", "VARCHAR", True),
            ColumnDef("iid", "VARCHAR", True),
            ColumnDef("company_key", "VARCHAR"),
            ColumnDef("status_date", "DATE", True),
            ColumnDef("isin", "VARCHAR"),
            ColumnDef("local_code_6", "VARCHAR"),
            ColumnDef("exchange_code", "INTEGER"),
            ColumnDef("exchange_desc", "VARCHAR"),
            ColumnDef("market_tier", "VARCHAR"),
            ColumnDef("security_status", "VARCHAR"),
            ColumnDef("company_status", "VARCHAR"),
            ColumnDef("active_flag", "BOOLEAN"),
            ColumnDef("shares_outstanding", "DOUBLE"),
            ColumnDef("monthend_flag", "BOOLEAN"),
            ColumnDef("fic", "VARCHAR"),
            ColumnDef("loc", "VARCHAR"),
            ColumnDef("source_relation", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("status_row_id",),
    ),
    TableDef(
        name="kr_relation_inventory",
        columns=(
            ColumnDef("relation_key", "VARCHAR", True),
            ColumnDef("library_name", "VARCHAR"),
            ColumnDef("relation_name", "VARCHAR"),
            ColumnDef("purpose", "VARCHAR"),
            ColumnDef("materialized_table", "VARCHAR"),
            ColumnDef("access_status", "VARCHAR"),
            ColumnDef("row_count", "BIGINT"),
            ColumnDef("issuer_count", "BIGINT"),
            ColumnDef("min_date", "DATE"),
            ColumnDef("max_date", "DATE"),
            ColumnDef("key_columns", "VARCHAR"),
            ColumnDef("market_coverage", "VARCHAR"),
            ColumnDef("notes", "VARCHAR"),
            ColumnDef("collected_at", "TIMESTAMPTZ"),
        ),
        primary_key=("relation_key",),
    ),
)

ALL_TABLES: tuple[TableDef, ...] = SOURCE_TABLES + CANONICAL_TABLES + VALIDATION_TABLES + KR_LAKE_TABLES

SCHEMA_BY_TABLE = {table.name: table for table in ALL_TABLES}


def create_all_tables_sql() -> Iterable[str]:
    """Yield CREATE TABLE statements for every WRDS table."""

    for table in ALL_TABLES:
        yield _create_table_sql(table)


def table_columns(table_name: str) -> tuple[str, ...]:
    """Return the ordered column names for a table."""

    table = SCHEMA_BY_TABLE[table_name]
    return tuple(column.name for column in table.columns)
